import type { Metadata } from "next";
import * as React from "react";
import { Raleway, Inter } from "next/font/google";

// React's ViewTransition is shipped (Next 16 `experimental.viewTransition`) but not
// yet in @types/react — access it safely with a Fragment fallback.
const ViewTransition =
  (React as unknown as {
    unstable_ViewTransition?: React.ComponentType<{ children?: React.ReactNode }>;
  }).unstable_ViewTransition ?? React.Fragment;
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import {
  PersonStructuredData,
  WebsiteStructuredData,
  ProfilePageStructuredData,
  FAQStructuredData,
  ProfessionalServiceStructuredData,
  SkillsItemListStructuredData,
} from "@/components/StructuredData";
import { GoogleAnalytics } from "@/components/Analytics";
import ScrollToTop from "@/components/ScrollToTop";
import CommandPalette from "@/components/CommandPalette";
import { Toaster } from "sonner";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { siteConfig, siteUrl } from "@/lib/site-config";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-raleway",
  display: "swap",
  preload: true,
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: `${siteConfig.name} | Frontend Developer & IT Lead — Next.js, TypeScript & AI Automation | Nairobi, Kenya`,
    template: `%s | ${siteConfig.name} — Frontend Developer & IT Lead`,
  },
  description: siteConfig.description,
  keywords: [
    "Geoffrey Muthoni",
    "Geoffrey Mwangi",
    "Frontend Developer Nairobi",
    "React Developer Kenya",
    "Next.js Developer",
    "WordPress Developer Nairobi",
    "Hire Frontend Developer Kenya",
    "Freelance Web Developer Kenya",
    "TypeScript Developer",
    "Supabase Developer",
    "Remote Frontend Developer",
    "Web Developer Portfolio",
  ],
  authors: [{ name: siteConfig.fullName, url: siteUrl }],
  creator: siteConfig.fullName,
  publisher: siteConfig.fullName,
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  icons: {
    icon: "/assets/navlogo.png",
    shortcut: "/assets/navlogo.png",
    apple: "/assets/navlogo.png",
  },
  openGraph: {
    title: `${siteConfig.name} | Frontend Developer & IT Lead — Next.js, TypeScript & AI Automation`,
    description: siteConfig.description,
    url: siteUrl,
    siteName: `${siteConfig.name} Portfolio`,
    // Social card image is generated by app/opengraph-image.tsx
    locale: "en_KE",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.name} | Frontend Developer & IT Lead`,
    description: siteConfig.tagline,
    creator: siteConfig.twitter,
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: siteUrl,
  },
  verification: {
    google: "v6CadcpqfPPbuZ1CdssdCYpb4s3jEsjiBkvkQ-lVmxo",
  },
  category: "technology",
  other: {
    "geo.region": "KE-30",
    "geo.placename": "Nairobi",
  },
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} ${inter.variable}`} suppressHydrationWarning>
      <head>
        <PersonStructuredData />
        <WebsiteStructuredData />
        <ProfilePageStructuredData />
        <FAQStructuredData />
        <ProfessionalServiceStructuredData />
        <SkillsItemListStructuredData />
        {process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID && (
          <GoogleAnalytics measurementId={process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID} />
        )}
      </head>
      <body className={raleway.className}>
        <ThemeProvider defaultTheme="dark" storageKey="portfolio-theme">
          <a
            href="#main-content"
            className="sr-only focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-[100] focus:px-4 focus:py-2 focus:bg-[--color-primary] focus:text-white focus:rounded-lg focus:outline-none focus:ring-2 focus:ring-[--color-primary] focus:ring-offset-2"
          >
            Skip to main content
          </a>
          <Navbar />
          <main id="main-content">
            <ViewTransition>{children}</ViewTransition>
          </main>
          <Footer />
          <ScrollToTop />
          <CommandPalette />
          <Toaster position="bottom-right" richColors />
          <Analytics />
          <SpeedInsights />
        </ThemeProvider>
      </body>
    </html>
  );
}
