import { Metadata } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://geoffreymuthoni.com';

export const metadata: Metadata = {
  title: "Resume - Professional Experience & Skills",
  description: "View Geoffrey Muthoni's professional resume. Frontend Developer and IT Lead with 4+ years of experience in Next.js, React, TypeScript, Supabase, and AI-powered automation. Available for remote and full-time opportunities.",
  keywords: [
    "Geoffrey Muthoni Resume",
    "Frontend Developer CV",
    "IT Lead Resume",
    "React Developer Resume",
    "Next.js Developer CV",
    "AI Automation Specialist",
    "Supabase Developer Resume",
    "Hire Frontend Developer",
  ],
  openGraph: {
    title: "Geoffrey Muthoni - Professional Resume",
    description: "Frontend Developer and IT Lead with 4+ years of experience in Next.js, React, TypeScript, Supabase, and AI-powered automation. View my experience, skills, and projects.",
    url: `${siteUrl}/resume`,
    type: "profile",
    // Social card image is generated by app/opengraph-image.tsx (inherited)
  },
  twitter: {
    card: "summary_large_image",
    title: "Geoffrey Muthoni - Professional Resume",
    description: "Frontend Developer & IT Lead. Next.js | TypeScript | Supabase | AI Automation.",
  },
  alternates: {
    canonical: `${siteUrl}/resume`,
  },
};

export default function ResumeLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}

